spring.application.name=Empresa
# URL a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/empresa?serverTimezone=UTC
# Credenciales de acceso
spring.datasource.username=karraspio
spring.datasource.password=1234
# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Estrategia de actualizacion
spring.jpa.hibernate.ddl-auto=update
# Muestra consultas SQL en consola ( debugging ) 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Muestra controladores que atienden peticion ( debug )
logging.level.org.springframework.web=DEBUG